version: '3.9'

services:
  db:
    container_name: weight_graph_db
    image: postgres:latest
    environment:
      POSTGRES_DB: weight_graph
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - weight_graph_db:/var/lib/postgresql/data

  api:
    container_name: weight_graph_api
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - ./api:/api

  front:
    container_name: weight_graph_front
    build:
      context: .
      dockerfile: Dockerfile.front
    depends_on:
      - api
    command: bash -c "npm run dev"
    volumes:
      - ./front:/front
    ports:
      - '8080:3000'

volumes:
  weight_graph_db:
