version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: weight_graph
      POSTGRES_USER: postgres
      POSRGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - weight_graph_db:/var/lib/postgresql/data

  api:
    build: api/
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - ./api:/api

  front:
    build: front/
    depends_on:
      - api
    command: npm run dev
    volumes:
      - ./front:/front

volumes:
  weight_graph_db:
